## auto en main para pruebas así más agilidad
trigger:
- main
## siempre por defecto ubuntu
pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Login en ACR
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: 'sc-ado-docker-lab'

## Aquí hago el buil y el push
- task: Docker@2
  displayName: Build and Push Image
  inputs:
    command: buildAndPush
    repository: react-hello-world
    dockerfile: '**/Dockerfile'
    containerRegistry: 'sc-ado-docker-lab'
    tags: |
      $(Build.BuildId)

# ---- Esta es la tarea para desplegar kubernetes, puedes ignorarla esta fuera de tu scope
- task: KubernetesManifest@1
  displayName: Deploy to AKS
  inputs:
    action: deploy
    connectionType: 'Azure Resource Manager'
    azureSubscriptionConnection: 'sc-ado-wif-lab' 
    azureResourceGroup: 'rg-aks-lab'
    kubernetesCluster: 'labaks'
    namespace: 'default'
    manifests: |
      **/deployment.yaml
    containers: |
      labacrtestamaia1238273.azurecr.io/react-hello-world:$(Build.BuildId)
