## auto en main para pruebas así más agilidad
trigger:
- main
## siempre por defecto ubuntu
pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Login en ACR
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: # pendiente que me de el valor mario 

## Aquí hago el buil y el push
- task: Docker@2
  displayName: Build and Push Image
  inputs:
    command: buildAndPush
    repository: react-hello-world
    dockerfile: '**/Dockerfile'
    containerRegistry: 'sc-acr-lab'
    tags: |
      $(Build.BuildId)

