## auto en main para pruebas así más agilidad
trigger:
- main

pool:
  name: ado-lab-pool
  demands: agent.name -equals ado-agent-vm

steps:
# 1. Login en ACR
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: 'sc-ado-docker-lab'

# 2. Build y Push con dos tags: BuildId + latest
- task: Docker@2
  displayName: Build and Push Image
  inputs:
    command: buildAndPush
    repository: react-hello-world
    dockerfile: '**/Dockerfile'
    containerRegistry: 'sc-ado-docker-lab'
    tags: |
      $(Build.BuildId)
      latest   # 👈 este es el que faltaba

# 3. Deploy a Kubernetes (igual que tenías)
- task: AzureCLI@2
  displayName: "Install kubectl + kubelogin locally"
  inputs:
    azureSubscription: sc-ado-wif-lab
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "📦 Instalando kubectl y kubelogin en ~/bin..."
      mkdir -p $HOME/bin
      curl -sSL -o $HOME/bin/kubelogin.zip https://github.com/Azure/kubelogin/releases/download/v0.2.10/kubelogin.zip
      unzip -o $HOME/bin/kubelogin.zip -d $HOME/bin/
      mv $HOME/bin/bin/linux_amd64/kubelogin $HOME/bin/kubelogin
      chmod +x $HOME/bin/kubelogin
      export PATH=$HOME/bin:$PATH

      echo "🔑 Obteniendo credenciales..."
      az aks get-credentials --resource-group rg-aks-lab --name labaks --overwrite-existing --file .kubeconfig-labaks
      export KUBECONFIG=.kubeconfig-labaks

      echo "🔄 Ajustando login..."
      kubelogin convert-kubeconfig -l azurecli

      echo "📦 Deployando..."
      kubectl apply -f deployment.yaml -n default --validate=false
